// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package smile_api

import (
	"github.com/99designs/gqlgen/graphql"
)

type Comment struct {
	ID        string     `json:"id"`
	Comment   string     `json:"comment"`
	CreatedAt int        `json:"createdAt"`
	Reply     []*Comment `json:"reply"`
}

type Comments struct {
	Node    string     `json:"node"`
	Total   int        `json:"total"`
	IsOpen  bool       `json:"isOpen"`
	Comment []*Comment `json:"comment"`
}

type Post struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Content      *string   `json:"content"`
	Creator      *User     `json:"creator"`
	Contributor  []*User   `json:"contributor"`
	CreatedAt    int       `json:"createdAt"`
	LastEditedat int       `json:"lastEditedat"`
	Thumbnail    string    `json:"thumbnail"`
	LastEdited   *User     `json:"lastEdited"`
	Rating       *Rating   `json:"rating"`
	Comments     *Comments `json:"comments"`
}

type Rating struct {
	ID       string `json:"id"`
	ParentID string `json:"parentID"`
	Share    int    `json:"share"`
	Views    int    `json:"views"`
}

type SetupField struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	FullName string         `json:"fullName"`
	Password string         `json:"password"`
	IsAdmin  bool           `json:"isAdmin"`
	Avatar   graphql.Upload `json:"avatar"`
}

type User struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	FullName string  `json:"fullName"`
	Password string  `json:"password"`
	Avatar   *string `json:"avatar"`
	IsAdmin  bool    `json:"isAdmin"`
	Post     []*Post `json:"post"`
}
