-- Your SQL goes here
CREATE TABLE smile.usr_smile (
  user_id CHAR(36) NOT NULL UNIQUE,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) UNIQUE,
  joinAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastEditedAt TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fullname VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255),
  isAdmin BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (user_id)
);