ALTER TABLE `smile`.`comment` DROP FOREIGN CN_TO_USER_AS_COMMENT;
ALTER TABLE `smile`.`comment` DROP FOREIGN CN_TO_POST_AS_COMMENT;
ALTER TABLE `smile`.`comment` DROP FOREIGN CN_TO_POST_AS_COMMENT_PARENT FOREIGN;
DROP TABLE `smile`.`comment`;
