CREATE TABLE `smile`.`comment` (
    id INT NOT NULL AUTO_INCREMENT,
    postId INT NOT NULL,
    userId CHAR(36),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    content LONGTEXT,
    reply_for_id INT NULL,
    PRIMARY KEY (id),
    CONSTRAINT CN_TO_USER_AS_COMMENT FOREIGN KEY (userId)
        REFERENCES usr_smile (user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT CN_TO_POST_AS_COMMENT FOREIGN KEY (postId)
        REFERENCES post (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CN_TO_POST_AS_COMMENT_PARENT FOREIGN KEY (reply_for_id)
        REFERENCES comment (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);


