-- Your SQL goes here
ALTER TABLE  `smile`.`embed`  
	ADD COLUMN game INT,
	ADD COLUMN movie INT,
	ADD CONSTRAINT CN_TO_GAME FOREIGN KEY (game)
		REFERENCES game (id)
		ON DELETE CASCADE ON UPDATE CASCADE,
	ADD CONSTRAINT CN_TO_MOVIE FOREIGN KEY (movie)
        REFERENCES movie (id)
        ON DELETE CASCADE ON UPDATE CASCADE;
